steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/mev-boost-payloads-etl",
        "-f",
        "./Dockerfile",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/mev-boost-payloads-etl"
