steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/enduring-art-304119/mev-boost-etl",
        "-f",
        "./Dockerfile.test",
        ".",
      ]
images:
  - "gcr.io/enduring-art-304119/mev-boost-etl"
