# Use an official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PROJECT_ID_PRIVATE "enduring-art-207419"
ENV LOGGING_LEVEL "INFO"
ENV DATASET_ID "mev_boost"
ENV BIDS_TABLE_ID_STAGING "bids_staging"
ENV TABLE_ID_STAGING "mev_boost_staging"
ENV BUCKET_NAME "mev-boost-bids"

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies (if any, remove if not needed)
RUN apt-get update && apt-get install -y --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy requirements file and install Python dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy your application code into the container
COPY ./app /app/

# Specify the command to run on container start
CMD ["python", "bids_transfer.py"]