apiVersion: apps/v1
kind: Deployment
metadata:
  name: mev-boost-bids-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: mev-boost-bids-etl
  template:
    metadata:
      labels:
        app: mev-boost-bids-etl
    spec:
      serviceAccountName: mev-boost-k8s-sa
      containers:
        - name: mev-boost-bids-container
          image: gcr.io/enduring-art-207419/mev-boost-bids-etl:latest
      nodeSelector:
        pool: mev-boost-node-pool
