# Use an official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV LOGGING_LEVEL "INFO"
ENV PROJECT_ID_PRIVATE "enduring-art-207419"
ENV DATASET_ID "mev_boost"
ENV CONFIG_TABLE_ID "etl_config"
ENV TABLE_ID_STAGING "bids_staging"
ENV POD_CONFIG_TABLE_ID "bids_k8s_config"
ENV BUCKET_NAME "mev-boost-bids"
ENV BATCH_SIZE_MB 50

# Set the working directory inside the container
WORKDIR /app

# Create a virtual environment in the container
# This environment is isolated from the global Python environment
RUN python -m venv venv

# Activate the virtual environment
ENV PATH="/app/venv/bin:$PATH"

# Install system dependencies (if any, remove if not needed)
RUN apt-get update && apt-get install -y --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy requirements file and install Python dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy your application code into the container
COPY ./src /app/

# Specify the command to run on container start
CMD ["python", "main_backload.py"]