steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'      
      - "gcr.io/$PROJECT_ID/mev-boost-bids-bau-etl"
      - '-f'
      - './Dockerfile.bau'
      - '.'
images:
  - "gcr.io/$PROJECT_ID/mev-boost-bids-bau-etl"
