steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/mev-boost-bids-transfer"
      - '--build-arg'
      - 'PROJECT_ID=$PROJECT_ID'
      - "-f"
      - "./Dockerfile.transfer"
      - "."     
images:
  - "gcr.io/$PROJECT_ID/mev-boost-bids-transfer"
