select  block_timestamp,
        relay,
        slot,
        parent_hash,
        block_hash,
        builder_pubkey,
        proposer_pubkey,
        proposer_fee_recipient,
        gas_limit,
        gas_used,
        value,
        num_tx,
        block_number,
        timestamp,
        timestamp_s,
        timestamp_ms,
        optimistic_submission
from `eden-data-private.mev_boost.bids`
group by  block_timestamp,
          relay,
          slot,
          parent_hash,
          block_hash,
          builder_pubkey,
          proposer_pubkey,
          proposer_fee_recipient,
          gas_limit,
          gas_used,
          value,
          num_tx,
          block_number,
          timestamp,
          timestamp_s,
          timestamp_ms,
          optimistic_submission having count(*) > 1